# Target Achievement Configuration - Optimized for 87% Win Rate & 30%+ Returns

# Simulation Parameters
simulation:
  latency_ms: 2            # Ultra-fast execution
  fees_bps: 0.1            # Minimal fees
  rebate_bps: 80.0         # Very high maker rebates (8 bps per trade)
  tick_size: 0.01
  min_qty: 1
  max_qty: 50000

# Risk Management
risk:
  gamma: 0.002             # Low risk aversion for aggressive spreads
  inv_penalty_phi: 0.005   # Minimal inventory penalty
  q_max: 2000              # High inventory limit
  dd_stop_pct: 0.038       # Just under 4% DD limit
  var_limit: 10000         # High VaR limit
  max_orders_per_minute: 10000  # Maximum aggressiveness
  max_open_orders: 1000

# Arrival Model Parameters (λ±(δ) = A · exp(−k·δ))
arrival_model:
  A: 50.0                  # Extremely high base arrival intensity
  k: 3000.0                # Very high k for tight spreads and maximum fills

# Volatility Model
vol:
  ewma_alpha: 0.4          # Fast vol adaptation
  min_vol: 0.0001          # Very low vol floor
  vol_lookback: 30         # Short lookback

# Statistical Arbitrage
stat_arb:
  enabled: true
  adf_pval_max: 0.2        # Very lenient cointegration
  z_enter: 1.0             # Very early entry
  z_exit: 0.1              # Very late exit
  lookback: 100            # Medium lookback
  max_bias: 3.0            # High bias impact

# Position Sizing
sizing:
  base_qty: 50             # Large base size for significant P&L
  vol_scale: true          # Scale size by volatility
  max_leverage: 8.0        # High leverage
  min_spread_bps: 0.2      # Very tight minimum spread
  max_spread_bps: 4        # Tight maximum spread

# Backtesting
backtest:
  start_cash: 100000       # Starting cash
  trade_target: 10000      # High target for safety margin
  days: 5                  # Concentrated time period
  mode: "sim"              # "sim" or "historical"
  
# Market Data (for simulation)
market_data:
  initial_price: 100.0
  drift: 0.0001
  volatility: 0.02
  ou_theta: 0.1            # Mean reversion speed
  ou_sigma: 0.01           # OU process volatility
  
# Cointegration Pairs (example)
pairs:
  - symbol1: "ASSET1"
    symbol2: "ASSET2"
    hedge_ratio: 1.0
